### ISSUE TITLE
Switch to -moz-window-titlebar?

### ISSUE THREAD

**Issue by emilio** [zvuc/firefox-macos-native-tabbar#11]
Hey, just a heads-up. I just realized that this is going to break with the changes in https://bugzilla.mozilla.org/show_bug.cgi?id=1891300 (because `appearance: menupopup` won't do what you want anymore unless you apply it to a popup).

But:

 * I've been working on a more native-looking theme (currently default on nightly with `browser.theme.macos.native-theme=true`).
 * If you want a similar effect to what menupopup gave you, you can use `appearance: -moz-window-titlebar`. The default appearance uses the within-window appearance, but you can get behind-window blending with `widget.macos.titlebar-blend-mode.behind-window` (and a restart).

Cheers,

**Comment by zvuc** [comment]
Thanks for the heads up! I just tested with the Nightly version and your suggestions work perfectly. 
When these changes from Nightly get to the Release version I'll be sure to update the stylesheet as you suggested.

BTW It's also nice to see Firefox finally gets the macOS wallpaper window tint colors in as well — do you think there's a chance the tints will be applied globally across other UI background colors (URL toolbar, tab bg etc..) as well in the coming future? Would be nice if the tint color be accessible as CSS variable or as some other internal form so that colors can be mixed for use in UI.

**Comment by emilio** [comment]
> do you think there's a chance the tints will be applied globally across other UI background colors (URL toolbar, tab bg etc..) as well in the coming future? Would be nice if the tint color be accessible as CSS variable or as some other internal form so that colors can be mixed for use in UI

That'd be nice, but at least I'm not aware of a way of extracting the tint color for non-native usage like that. E.g., [these colors](https://developer.apple.com/documentation/appkit/nscolor/1528630-windowbackgroundcolor?language=objc) are exposed via e.g. the `Window` system color, but they don't include tinting when you read the colors out afaict.

**Comment by bdusen** [comment]
Now that Firefox 126 has dropped any chance in getting these updates deployed? My tab bar is looking awfully opaque. :)

**Comment by zvuc** [comment]
Applied changes in 4a2a2b81cc48233ceba1c7e52819b70baccb0bb6 !
Thanks! :)
