### ISSUE TITLE
Dark mode foreground tab is indistinguishable when windows in in focus

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [zvuc/firefox-macos-native-tabbar#6]
<img width="931" alt="image" src="https://github.com/zvuc/firefox-macos-native-tabbar/assets/11556527/db3301cd-a91b-419f-b02b-c8f2877eba7a">

Macos 12.7
Firefox 120

Thank you

**Comment by zvuc** [comment]
This is not really a bug but rather a side-effect of the translucent tabbar tweak that only happens when your Firefox window is over a certain (bright) color background. If the underlying background (whether it be the wallpaper or another app) has a similar color as Firefox's default dark UI gray color, the tab will turn out to look awfully similar to the tab bar color making it hard to distinguish the two. 

A workaround could be adding additional borders for tabs, but I opted not to to so because I only wanted to add translucency to the tab bar in this tweak, and refrain customizing other aspects of the default Firefox skin too much.

**Comment by zvuc** [comment]
Actually, I just realized that the thin border I had added previously to alleviate this exact issue wasn't displaying at all at the moment. It must have broke at some point and I didn't see it. Sorry for the confusion, I'll push a fix now that brings back the border.
