### ISSUE TITLE
Can we make toolbar (below tabbar) opaque also?

### ISSUE THREAD

**Issue by caongocthai** [zvuc/firefox-macos-native-tabbar#8]
I have got the tabbar opaque. However, the toolbar (right below tabbar) is still not. Is it possible to get that bar opaque?

**Comment by zvuc** [comment]
I think you mean transparent (translucent) not opaque.

It's an intentional design choice, because macOS native apps also tend to have translucent areas along with opaque bars. 
<img width="472" alt="image" src="https://github.com/zvuc/firefox-macos-native-tabbar/assets/2870726/f2ee1516-80ba-4f47-9244-ce7e43aab0ce">

It also has to do with the fact that I'm using the translucent tabbar tweak with my other tweak here (https://github.com/zvuc/firefox-sliding-bookmarks-bar/), and that requires the navbar be opaque because the bookmarks bar hides under it.

Giving an option for the user to choose whether navbar should be translucent too could be a choice, but I don't want to overcomplicate things, and I think there are many other tweaks that make literally everything translucent (which in my personal opinion doesn't look that good) so if that's what you're leaning towards, please look for other options by other people 😃
